file=open('Codingal.txt','r')
print("reading the first line........")
print(file.readline())
file.close()
file=open('Codingal.txt','r')
print("read multiple lines.....")
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file=open('Codingal.txt','r')
print ("looping through the lines...")
for line in file:
    print(line)
file.close()
